repos:
  - repo: local
    hooks:
      - id: uv-format
        name: uv format
        entry: uv
        args: ["format"]
        language: system
        pass_filenames: false
      - id: uv-ruff-check
        name: uv ruff check --fix
        entry: uv
        args: ["tool", "run", "ruff", "check", "--fix"]
        language: system
        types: [python]
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo
        args: ["fmt"]
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo
        args: [
          "clippy",
          "--workspace",
          "--all-targets",
        ]
        language: system
        pass_filenames: false
